[package]
name = "generate-headers"
version = "0.1.0"
edition = "2018"

[dependencies]
cbindgen = "0.24.0"
textwrap = "=0.16.1"
once_cell = "=1.20.3"
unicode-width = "=0.1.13"
quote = "=1.0.41"
syn = "=2.0.106"
